### ISSUE TITLE
Doesn't work on replit

### ISSUE THREAD

**Issue by hackinghacker1** [caracal-js/Incognito#2]
I tried to import this from GitHub on Replit and whenever I try to go to any site it just shows a white screen.

**Comment by LucasOnChromeOS** [comment]
Same here, and I believe its because it needs to have a special version build for replit. Although now, there arent any.

**Comment by Adithr123** [comment]
@caracal-js Can u pls fix?

**Comment by hackinghacker1** [comment]
@LucasOnChromeOS I actually think it's because it needs to have a server to connect to

**Comment by AbkHacks12** [comment]
So i imported it to replit and it showed like the incognito then i tested it i searched up discord and it kept loading for like a and 1 hour staright so i'm not sure ig you can make a version for replit or fix it

**Comment by ineifujimura** [comment]
please leave this poor developer alone find out how to make your own proxy

**Comment by hackinghacker1** [comment]
> please leave this poor developer alone find out how to make your own proxy

well isn't the point of developing fixing your msitakes?

**Comment by Adithr123** [comment]
> please leave this poor developer alone find out how to make your own proxy

The point of issues are to let the dev know that there is an error. Its not to bug them, its just to let them know.

**Comment by hackinghacker1** [comment]
I wasn't bugging him, I was just explaining my issue
