### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by depthso** [caracal-js/Incognito#8]
What script do I need to run and what packages do I need? @caracal-js

**Comment by ZeltuxDev** [comment]
If you go to Titanium Networks Github you can find a deployable version of ultraviolet [https://github.com/titaniumnetwork-dev/Ultraviolet-Node/wiki/Run-on-Replit]

**Comment by depthso** [comment]
Thanks for the info, I have replaced the Ultraviolet files with the ones from Incognito and it works fantastic!
